export default function Terms() {
  return (
    <main className="max-w-3xl mx-auto px-4 py-10 text-gray-800 dark:text-gray-200">
      <h1 className="text-3xl font-bold mb-6">Terms of Service</h1>

      <p className="mb-4 text-sm text-gray-500 dark:text-gray-400">
        Last updated: March 28, 2025
      </p>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">1. Acceptance of Terms</h2>
        <p>
          By accessing or using Memi Chat (&ldquo;the App&rdquo;), you agree to
          be bound by these Terms of Service (&ldquo;Terms&rdquo;). If you do
          not agree to these Terms, please do not use the App.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">
          2. Description of Service
        </h2>
        <p>
          Memi Chat is an AI-powered messaging app that allows users to interact
          with custom AIs, create personalities, and explore multi-agent
          conversations and debates.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">3. User Responsibilities</h2>
        <ul className="list-disc list-inside space-y-2">
          <li>You must be at least 13 years old to use Memi Chat.</li>
          <li>
            You are responsible for any content you submit, including custom AI
            personalities, chat inputs, and data uploads.
          </li>
          <li>
            You agree not to use the App for any unlawful, harmful, or abusive
            purposes.
          </li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">4. AI-Generated Content</h2>
        <p>
          The content generated by AIs in the app may be fictional, biased, or
          unpredictable. We do not guarantee the accuracy or appropriateness of
          AI responses. Use discretion and report any harmful behavior.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">5. Privacy</h2>
        <p>
          Our use of your data is governed by our{" "}
          <a
            href="/privacy"
            className="text-blue-600 dark:text-blue-400 underline"
          >
            Privacy Policy
          </a>
          . By using the App, you consent to the collection and use of your
          information as described.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">6. Termination</h2>
        <p>
          We reserve the right to suspend or terminate your access to the App at
          any time, for any reason, without notice.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">7. Modifications</h2>
        <p>
          We may update these Terms from time to time. Continued use of the App
          after changes means you accept the new Terms.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">8. Contact Us</h2>
        <p>
          If you have questions about these Terms, please contact us at{" "}
          <a
            href="mailto:support@memichat.com"
            className="text-blue-600 dark:text-blue-400 underline"
          >
            support@memichat.com
          </a>
          .
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">
          9. User-Generated Content
        </h2>
        <p>
          You retain ownership of the content you create or submit in Memi Chat.
          By using the App, you grant us a non-exclusive, worldwide,
          royalty-free license to use, reproduce, and display your content
          solely for operating and improving the App. You are solely responsible
          for ensuring that your content does not violate any applicable laws or
          rights of others.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">10. AI Limitations</h2>
        <p>
          The responses provided by AI in Memi Chat are generated by algorithms
          and may contain errors, inaccuracies, or offensive content. These
          outputs do not reflect the opinions of Memi Chat and should not be
          relied upon for professional advice (legal, medical, financial, etc.).
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">11. Mobile Platforms</h2>
        <p>
          If you access Memi Chat via a mobile application, you acknowledge that
          your use is also subject to the terms of the Apple App Store or Google
          Play Store. Memi Chat is solely responsible for its content; platform
          providers are not responsible for support, claims, or losses related
          to the app.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">
          12. Prohibited Activities
        </h2>
        <ul className="list-disc list-inside space-y-2">
          <li>Using the App to harass, abuse, or harm others.</li>
          <li>
            Uploading malware or attempting to reverse-engineer the service.
          </li>
          <li>Using the App to generate harmful or unlawful content.</li>
          <li>Violating intellectual property or privacy rights of others.</li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">13. Governing Law</h2>
        <p>
          These Terms are governed by and construed in accordance with the laws
          of EU, without regard to conflict of law principles. Any disputes
          arising under these Terms shall be subject to the exclusive
          jurisdiction of the courts in EU.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">
          14. Disclaimer of Warranty
        </h2>
        <p>
          Memi Chat is provided &ldquo;as is&rdquo; and &ldquo;as
          available&rdquo; without warranties of any kind. We do not guarantee
          that the App will be secure, error-free, or available at all times.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">
          15. Limitation of Liability
        </h2>
        <p>
          To the fullest extent permitted by law, Memi Chat shall not be liable
          for any indirect, incidental, special, or consequential damages
          resulting from your use of the App.
        </p>
      </section>
    </main>
  );
}
