const tintColorLight = "#0a7ea4";
const tintColorDark = "#fff";

export const Colors = {
  light: {
    text: "#303030",
    background: "#fff",
    tint: tintColorLight,
    icon: "#687076",
    tabIconDefault: "#687076",
    tabIconSelected: tintColorLight,
    chatInputBackground: "#fff",
    chatInputText: "#11181C",
    chatInputPlaceholder: "#687076",
    chatHeaderBottomBorder: "#f2f2f2",
    messageBackground: "#f2f2f2",
    bottomSheetBackground: "#f2f2f2",
    agentSelectionBackground: "#f6f6f6",
    agentSelectionTitleText: "#1c1c1e",
    agentSelectionDescriptionText: "#69696b",
    agentSelectionRowBg: "#fff",
    agentSelectionRowDescription: "#848487",
    editAgentInputBackground: "#fff",
    chatToolbarToolBorder: "#ededed",
    chatToolbarSendIconBg: "#000",
    chatToolbarSendIconColor: "#fff",
    drawerItemActiveBg: "#f6f6f6",
    allChatsText: "#919191",
    drawerSettingsIcon: "#f2f2f2",
    promptHelpTitle: "#11181C",
    promptHelpDescription: "#687076",
    settingsItemContainerBg: "#fff",
    settingsBackground: "#f5f5f5",
  },
  dark: {
    text: "#ECEDEE",
    background: "#000",
    tint: tintColorDark,
    icon: "#9BA1A6",
    tabIconDefault: "#9BA1A6",
    tabIconSelected: tintColorDark,
    chatInputBackground: "#1e1e1e",
    chatInputText: "#ECEDEE",
    chatInputPlaceholder: "#9BA1A6",
    chatHeaderBottomBorder: "#333333",
    messageBackground: "#1e1e1e",
    bottomSheetBackground: "#1e1e1e",
    agentSelectionBackground: "#1c1c1e",
    agentSelectionTitleText: "#a9a9b0",
    agentSelectionDescriptionText: "#7a7a80",
    agentSelectionRowBg: "#2c2c2e",
    agentSelectionRowDescription: "#9e9ea5",
    editAgentInputBackground: "#121212",
    chatToolbarToolBorder: "#333333",
    chatToolbarSendIconBg: "#fff",
    chatToolbarSendIconColor: "#000",
    drawerItemActiveBg: "#222222",
    allChatsText: "#919191",
    drawerSettingsIcon: "#424242",
    promptHelpTitle: "#ECEDEE",
    promptHelpDescription: "#9BA1A6",
    settingsItemContainerBg: "#2c2c2e",
    settingsBackground: "#000",
  },
};
